site_name: Poignant Guide to Python
site_url: https://poignant.dev
theme:
  name: material
  features:
    - navigation.footer
    - content.code.copy

  logo: assets/snake-logo-small.png
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/custom_sidebar.css
  - stylesheets/extra.css  

extra_javascript:
  - js/pycon-copy.js
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: pycon
          class: pycon
          validator: "pymdownx.superfences.file_validator"
          format: "pymdownx.superfences.strip_primary_formatter"
extra:
  generator: false

  