site_name: Poignant Guide to Python
site_url: https://poignant.dev
theme:
  name: material
  features:
    - navigation.footer
    - content.code.copy
    - navigation.expand  
    - toc.integrate
  logo: assets/snake-logo-small.png
  favicon: assets/favicon.ico

nav:
  - Prologue: prologue.md
  - Introduction: introduction.md
  - 1. A Quick (and Hopefully Painless) Ride Through Python (with Cartoon Foxes): chapter-1.md
  - 2. Floating Little Leaves of Code: chapter-2.md
  - 3. Them What Make the Rules and Them What Live the Dream : chapter-3.md 
  - 4. Advanced Organ Instructing: chapter-4.md
  - 5. Downtown: chapter-5.md
  - 6. A Sponsored Dragon-Slaying: chapter-6.md
  - + Expansion Paks +:
    - The Tiger's Vest (Installing Python): installing-python.md


extra_css:
  - stylesheets/custom_sidebar.css
  - stylesheets/extra.css  

extra_javascript:
  - js/pycon-copy.js
  
markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: pycon
          class: pycon
          validator: "pymdownx.superfences.file_validator"
          format: "pymdownx.superfences.strip_primary_formatter"
extra:
  generator: false

  