site_name: Poignant Guide to Python
site_url: https://sitename.example
theme:
  name: material
  features:
    - navigation.footer
  logo: assets/snake-logo-small.png
  favicon: assets/favicon.ico

extra_css:
  - stylesheets/custom_sidebar.css
  - stylesheets/extra.css  

markdown_extensions:
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  generator: false